### PR TITLE
fix/all: fix validation of Owners before PUT for all data types and rename mock vault file

### LINKED ISSUE #885: Owners field must be validated before PUT
The owner(s) field of the immutable / mutable / append-only data should be validated before storing it in the mock vault.

The owner field in the data struct should be validated against the public_key of the PublicId that is held by routing(soon to be replaced by quic-p2p).
For requests by an App, it should be validated against the owner field of the public Id.
This is already extracted from the PublicId [here](https://github.com/maidsafe/safe_client_libs/blob/c999a9a4028271dc885b2600974959b481b03675/safe_core/src/client/mock/vault.rs#L346)

### PR DESCRIPTION
**Pull request by Yoga07**
Resolves #885 and #889 

- Fixes new mutable data safe_app tests
- Adds tests for validation of owners before PUTs
- Renames mock vault file name to 'SCL-Mock'

### CODE REVIEW

File: safe_app/src/tests/unpublished_mutable_data.rs [hunk 1]
```diff
@@ -230,7 +232,7 @@ fn md_created_by_app_2() {
                 DIR_TAG,
                 data,
                 permissions,
-                PublicKey::from(unwrap!(client.public_bls_key())),
+                PublicKey::from(unwrap!(client.owner_key())),
```
Comment (lionel1704) [inline safe_app/src/tests/unpublished_mutable_data.rs]: `client.owner_key()` will return a `safe_nd::PublicKey` so this might return a clippy error

File: safe_core/src/client/mock/vault.rs [hunk 2]
```diff
@@ -37,10 +37,7 @@ pub enum Data {
     AppendOnly(AData),
 }
 
-const FILE_NAME: &str = "MockVault";
-lazy_static! {
```
Comment (lionel1704) [inline safe_core/src/client/mock/vault.rs]: Looks like this block has been removed by mistake :smile_cat:

File: safe_core/src/client/mod.rs [hunk 3]
```diff
@@ -2034,9 +2039,20 @@ mod tests {
                     // Put idata
                     client2.put_pub_idata(data.clone())
                 })
+                .and_then(move |_| {
+                    client3
+                        .put_unpub_idata(test_data.clone())
+                        .then(|res| match res {
+                            Ok(_) => panic!("Verifying owners failed"),
```
Comment (lionel1704) [inline safe_core/src/client/mod.rs]: Maybe also mention `Unexpected Success` in the panic message

File: safe_core/src/client/mod.rs [hunk 4]
```diff
@@ -2965,13 +3001,33 @@ mod tests {
...
             client
                 .put_adata(AData::UnpubSeq(data.clone()))
                 .map(move |res| {
                     assert_eq!(res, ());
                 })
                 .and_then(move |_| {
                     client1
+                        .put_adata(AData::UnpubSeq(test_data.clone()))
+                        .then(|res| match res {
+                            Ok(_) => panic!("Verifying owner failed"),
```
Comment (lionel1704) [inline safe_core/src/client/mod.rs]: One more here.

File: safe_core/src/client/mock/vault.rs [hunk 5]
```diff
@@ -390,12 +390,25 @@ impl Vault {
                 Response::GetIData(result)
             }
             Request::PutIData(idata) => {
-                let result = self.put_data(
-                    DataId::Immutable(*idata.address()),
-                    Data::Immutable(idata),
-                    requester,
-                );
-                Response::Mutation(result)
+                if let IData::Unpub(data) = idata.clone() {
```
Comment (lionel1704) [inline safe_core/src/client/mock/vault.rs]: This can be refactored a bit. Something like:
```
                let result = {
                    if let IData::Unpub(data) = idata.clone() {
                        if owner_pk != *data.owner() {
                            return Err(SndError::InvalidOwners);
                        }
                    }
                    self.put_data(
                        DataId::Immutable(*idata.address()),
                        Data::Immutable(idata),
                        requester,
                    )
                };
                Response::Mutation(result)
```
Reduces duplicate code :smile:

File: safe_core/src/client/mod.rs [hunk 6]
```diff
@@ -2583,15 +2600,33 @@ mod tests {
...
                 .put_seq_mutable_data(data.clone())
                 .and_then(move |res| {
                     assert_eq!(res, ());
                     Ok(())
                 })
+                .and_then(move |_| {
+                    client1
+                        .put_seq_mutable_data(test_data.clone())
+                        .then(|res| match res {
+                            Ok(_) => panic!("Verifying owners failed"),
```
Comment (lionel1704) [inline safe_core/src/client/mod.rs]: Here too.

File: safe_core/src/client/mod.rs [hunk 7]
```diff
@@ -2034,9 +2039,20 @@ mod tests {
                     // Put idata
                     client2.put_pub_idata(data.clone())
                 })
+                .and_then(move |_| {
+                    client3
+                        .put_unpub_idata(test_data.clone())
+                        .then(|res| match res {
+                            Ok(_) => panic!("Unexpected Success: Validating owners has failed"),
```
Comment (m-cat) [inline safe_core/src/client/mod.rs]: Shouldn't this say "Validating owners should fail" instead of "has failed"?

File: safe_core/src/client/mod.rs [hunk 8]
```diff
@@ -2583,15 +2606,33 @@ mod tests {
...
                 .put_seq_mutable_data(data.clone())
                 .and_then(move |res| {
                     assert_eq!(res, ());
                     Ok(())
                 })
+                .and_then(move |_| {
+                    client1
+                        .put_seq_mutable_data(test_data.clone())
+                        .then(|res| match res {
+                            Ok(_) => panic!("Unexpected Success: Validating owners has failed"),
```
Comment (m-cat) [inline safe_core/src/client/mod.rs]: Same here.

File: safe_core/src/client/mod.rs [hunk 9]
```diff
@@ -2965,13 +3035,33 @@ mod tests {
...
             client
                 .put_adata(AData::UnpubSeq(data.clone()))
                 .map(move |res| {
                     assert_eq!(res, ());
                 })
                 .and_then(move |_| {
                     client1
+                        .put_adata(AData::UnpubSeq(test_data.clone()))
+                        .then(|res| match res {
+                            Ok(_) => panic!("Unexpected Success: Validating owners has failed"),
```
Comment (m-cat) [inline safe_core/src/client/mod.rs]: Same here.

File: safe_core/src/client/mock/vault.rs [hunk 10]
```diff
@@ -586,13 +596,17 @@ impl Vault {
...
-                );
-                Response::Mutation(result)
+                if data.owner() == owner_pk {
+                    let address = *data.address();
+                    let result = self.put_data(
+                        DataId::Mutable(address),
+                        Data::NewMutable(data.clone()),
+                        requester,
+                    );
+                    Response::Mutation(result)
```
Comment (m-cat) [inline safe_core/src/client/mock/vault.rs]: Instead of returning `Response::Mutation` in two different spots, maybe we should follow the pattern used elsewhere and only return it once. So something like:

```rust
let result = if ... {
    ...
} else {
    ...
};
Response::Mutation(result)
```

File: safe_core/src/client/mock/vault.rs [hunk 11]
```diff
@@ -857,13 +871,18 @@ impl Vault {
...
-                Response::Mutation(result)
+                let owner_idx = adata.owners_index();
+                if unwrap!(adata.get_owners(owner_idx - 1)).public_key == owner_pk {
+                    let address = *adata.address();
+                    let result = self.put_data(
+                        DataId::AppendOnly(address),
+                        Data::AppendOnly(adata),
+                        requester,
+                    );
+                    Response::Mutation(result)
```
Comment (m-cat) [inline safe_core/src/client/mock/vault.rs]: Same comment as above.

File: safe_core/src/client/mock/vault.rs [hunk 12]
```diff
@@ -857,12 +871,17 @@ impl Vault {
...
             //
             Request::PutAData(adata) => {
+                let owner_idx = adata.owners_index();
                 let address = *adata.address();
-                let result = self.put_data(
-                    DataId::AppendOnly(address),
-                    Data::AppendOnly(adata),
-                    requester,
-                );
+                let result = if unwrap!(adata.get_owners(owner_idx - 1)).public_key != owner_pk {
```
Comment (lionel1704) [inline safe_core/src/client/mock/vault.rs]: Can you remove this `unwrap!` please?
