### PR TITLE
fix/all: disable AppClients from accessing Auth Keys

### LINKED ISSUE #896: Apps should not be able to send requests to get / mutate auth keys
Currently, 
- `list_auth_keys`
- `delete_auth_key`
- `insert_auth_key`
are all functions of the `Client` trait. Apps should not be allowed to perform such operations. So this can be removed from the `Client` trait and into the `AuthClient` and `CoreClient` for testing.

### PR DESCRIPTION
**Pull request by Yoga07**
Resolves #896 and #897 

- Introduces a new trait implementing functions which are not supposed to be called by AppClients
- Adapts safe_authenticator to the new impl
- Fixes tests for auth keys

### CODE REVIEW

File: safe_core/src/client/mod.rs [hunk 1]
```diff
@@ -1735,6 +1687,66 @@ pub fn wallet_transfer_coins(
...
 }
 
+/// Trait for manipulating Auth Keys
+pub trait AuthKeys: Clone + 'static {
+    /// Fetches a list of authorised keys and version in MaidManager.
+    fn list_auth_keys_and_version(
+        &self,
+    ) -> Box<CoreFuture<(BTreeMap<PublicKey, AppPermissions>, u64)>>
+    where
+        Self: Client,
```
Comment (m-cat) [inline safe_core/src/client/mod.rs]: I'm confused, is this saying that `Self` must implement the `Client` trait? Why not have `AuthKeys` depend on `Client` (i.e. `AuthKeys: Client + Clone + 'static`)? Also, it is not immediately clear why this is separate from `Client` in the first place (unless one reads the associated issue). Can you add some documentation in this module addressing these design decisions?
